#
# Nuber.io
# Copyright 2020 - 2021 Jamiel Sharief
#
# SPDX-License-Identifier: AGPL-3.0
#
# @copyright   Copyright (c) Jamiel Sharief
# @link        https://www.nuber.io
# @license     https://opensource.org/licenses/AGPL-3.0 AGPL-3.0 License
#
version: "2"
services:
  nuber:
    build: .
    ports:
      - "3000:443"
    volumes:
      - .:/var/www
  websocket:
    build: ./websocket
    depends_on:
      - nuber
    expose:
      - "8080"
    volumes:
      - .:/var/www
